[package]
name = "boba-engine"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
env_logger = "0.11"
boba-3d = { path = "./crates/boba-3d" }
boba-core = { path = "./crates/boba-core" }
